apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment-2
  name: nginx-deployment-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment-2
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment-2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}